name: NerdMessage
version: ${project.version}
description: ${project.description}
author: Deaygo Jarkko
main: nu.nerd.nerdmessage.NerdMessage

permissions:
    nerdmessage.message:
        description: Send a message to another player
        default: true

commands:
    msg:
        aliases: [m, r, reply, tell]
        description: Send a message to a user.
        permission: nerdmessage.message
        usage: |
           /msg <user> <message>: Send a message to a player
